---
  - hosts: all
    remote_user: ec2-user
    become: true
    gather_facts: no
    ignore_errors: true 
    tasks: 
        - name: Install Java
          yum: name=java-11-openjdk-devel state=present
        - name: Copy file with owner & permissions
          copy:
            src: /var/lib/jenkins/workspace/Devops/Final-project/java-program/target/
            dest: /tmp/
            owner: root
            group: root
            mode: '0777'